import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  Avatar,
  Button,
  Card,
  Dropdown,
  Modal,
  Steps,
  Tabs,
  Theme,
  Toggle
} from "react-daisyui";
import {signOut,useSession} from "next-auth/react"
import { getSession } from 'next-auth/react'
export default function Home() {
  const {data: session,status :sessionStatus} = useSession();
  console.log(session);
  console.log(JSON.stringify(session));
  return (
    <>
      <Head>
        <title>Bagus loh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-screen bg-base-200">
  <div className="hero-content text-center">
    <div className="max-w-md">
      <h1 className="text-5xl font-bold">Hello there</h1>
      <p className="py-6">
        Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
        excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a
        id nisi.
      </p>
  
      
      <button className="btn btn-primary">Get Started</button>
     
    </div>
  </div>
</div>

    </>
  )
}
